openapi: 3.0.0
info:
  description: DART's CDR Retrieval API
  version: 0.0.1
  title: CDR Retrieval API
  contact:
    email: john.hungerford@twosixlabs.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
servers:
  - url: https://darthost/dart/api/v1/cdrs
paths:
  /{doc-id}:
    get:
      summary: Retrieve CDR document
      parameters:
        - in: path
          description: CDR id (md5 hash of raw document)
          name: doc-id
          required: true
          schema:
            type: string
        - in: query
          description: Tenant from which to retrieve document (defaults to global corpus)
          name: tenantId
          required: false
          schema:
            type: string
        - in: query
          description: Latest timestamp of cdr version (defaults to current date)
          name: date
          required: false
          schema:
            type: string
        - in: query
          description: Include annotations?
          name: annotations
          required: false
          schema:
            type: boolean
            default: true
      security:
        - httpAuth: []
      responses:
        '200':
          description: Successful retrieval
          content:
            application/json:
              schema:
                $ref: 'https://raw.githubusercontent.com/WorldModelers/Document-Schema/master/cdr-schema/cdr-v3.json'
        '400':
          description: 'Bad request: malformed query parameters'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/failure_response'
        '401':
          description: Authentication token missing or invalid
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/failure_response'
        '403':
          description: User not authorized for this operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/failure_response'
        '404':
          description: 'No CDR exists with given document id with version on or prior to given date'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/failure_response'
        '503':
          description: Unable to reach canonical data store
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/failure_response'
  /raw/{doc-id}:
    get:
      summary: Retrieve raw document
      parameters:
        - in: path
          description: raw document ID
          name: doc-id
          required: true
          schema:
            type: string
        - in: query
          description: Tenant from which to retrieve document (defaults to global corpus)
          name: tenantId
          required: false
          schema:
            type: string
      security:
        - httpAuth: [ ]
      responses:
        '200':
          description: Successful retrieval
          content:
            application/octet-stream:
              schema:
                type: string
                format: byte
                description: file content of the requested output
        '400':
          description: 'Bad request'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/failure_response'
        '401':
          description: Authentication token missing or invalid
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/failure_response'
        '403':
          description: User not authorized for this operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/failure_response'
        '404':
          description: 'No document exists with given ID'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/failure_response'
        '503':
          description: Unable to reach canonical data store
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/failure_response'

  /archive:
    get:
      summary: Get a snapshot of the entire CDR datastore as a zip file
      security:
        - httpAuth: [ ]
      responses:
        '200':
          description: Successful retrieval
          content:
            application/zip:
              schema:
                type: string
                format: binary
        '401':
          description: Authentication token missing or invalid
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/failure_response'
        '403':
          description: User not authorized for this operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/failure_response'
        '503':
          description: Unable to reach canonical data store
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/failure_response'
  /archive/{tenantId}:
    get:
      summary: Get a snapshot of an entire tenant corpus as a zip file
      parameters:
        - in: path
          description: Identifier of desired corpus tenant
          name: tenantId
          required: true
          schema:
            type: string
      security:
        - httpAuth: [ ]
      responses:
        '200':
          description: Successful retrieval
          content:
            application/zip:
              schema:
                type: string
                format: binary
        '401':
          description: Authentication token missing or invalid
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/failure_response'
        '403':
          description: User not authorized for this operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/failure_response'
        '503':
          description: Unable to reach canonical data store
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/failure_response'
components:
  schemas:
    failure_response:
      type: object
      required:
        - status
        - error
      properties:
        status:
          description: the HTTP response status
          type: number
        error_message:
          description: explanation of failure
          type: string
  securitySchemes:
    httpAuth:
      type: http
      scheme: bearer
